"""Script to generate all 12 Jupyter notebooks."""
import json
import os

def make_nb(cells):
    return {
        "nbformat": 4, "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"}
        },
        "cells": cells
    }

def md(lines):
    if isinstance(lines, str):
        lines = lines.split("\n")
    return {"cell_type": "markdown", "metadata": {}, "source": [l + "\n" for l in lines[:-1]] + [lines[-1]]}

def code(lines):
    if isinstance(lines, str):
        lines = lines.split("\n")
    return {"cell_type": "code", "metadata": {}, "source": [l + "\n" for l in lines[:-1]] + [lines[-1]], "outputs": [], "execution_count": None}

def save_nb(filename, cells):
    nb = make_nb(cells)
    with open(filename, "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"Created {filename}")


# ============================================================
# NB01 — Data Ingestion & EDA
# ============================================================
save_nb("NB01_data_ingestion_eda.ipynb", [
md(["# NB01 — Data Ingestion & Exploratory Analysis",
    "",
    "**Objectives**: Download 20 tickers + benchmarks + macro, handle SQ→XYZ transition,",
    "compute base features, summary statistics, correlation heatmaps, drawdown analysis.",
    "",
    "**Output**: `master_data.parquet`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "import seaborn as sns",
      "from src.config import *",
      "from src.data_loader import *",
      "from src.feature_engineering import *",
      "from src.visualization import *",
      "import logging",
      "logging.basicConfig(level=logging.INFO)",
      "print('Imports OK')"]),
md(["## 1. Data Download",
    "Download all 20 tickers, benchmarks, VIX/VVIX, FRED macro. Handle SQ→XYZ merger."]),
code(["# Download all stock tickers",
      "raw_data = download_all_tickers()",
      "print(f'Downloaded {len(raw_data)} tickers')",
      "",
      "# Merge SQ → XYZ (Block Inc ticker change 2025-01-21)",
      "xyz_merged = merge_sq_xyz()",
      "raw_data['XYZ'] = xyz_merged",
      "print(f'XYZ merged: {len(xyz_merged)} rows')",
      "",
      "# Benchmarks",
      "bench_data = download_benchmarks()",
      "print(f'Downloaded {len(bench_data)} benchmarks')"]),
md(["## 2. Data Quality Checks",
    "Forward-fill ≤5 days, flag NaNs, detect |return| > 25% spikes."]),
code(["adj_close, flags = build_adj_close_panel(raw_data)",
      "print(f'Panel: {adj_close.shape[0]} days × {adj_close.shape[1]} tickers')",
      "print(f'Range: {adj_close.index[0].date()} to {adj_close.index[-1].date()}')",
      "print('\\nMissing values:', adj_close.isna().sum().sum())",
      "",
      "# Short-history tickers",
      "for t, ipo in SHORT_HISTORY_TICKERS.items():",
      "    n = adj_close[t].dropna().shape[0]",
      "    print(f'{t}: IPO/DPO {ipo}, {n} observations')"]),
md(["## 3. Returns"]),
code(["log_returns = compute_log_returns(adj_close)",
      "simple_returns = compute_simple_returns(adj_close)",
      "print('Log returns:', log_returns.shape)"]),
md(["## 4. Summary Statistics"]),
code(["stats_table = summary_statistics(log_returns[TICKERS])",
      "stats_table"]),
md(["## 5. Stationarity Tests (ADF + KPSS)"]),
code(["stat_tests = stationarity_table(log_returns[TICKERS])",
      "stat_tests"]),
md(["## 6. Cumulative Returns"]),
code(["fig = plot_cumulative_returns(adj_close[TICKERS], save_name='nb01_cumulative_returns')",
      "plt.show()"]),
md(["## 7. Correlation Heatmap"]),
code(["corr = log_returns[TICKERS].corr()",
      "fig = plot_correlation_heatmap(corr, save_name='nb01_correlation')",
      "plt.show()"]),
md(["## 8. Drawdown Analysis"]),
code(["dd_stats = []",
      "for t in TICKERS:",
      "    p = adj_close[t].dropna()",
      "    if len(p) < 2: continue",
      "    dd_stats.append({'ticker': t, 'max_drawdown': max_drawdown(p), 'calmar': calmar_ratio(p)})",
      "dd_df = pd.DataFrame(dd_stats).set_index('ticker').sort_values('max_drawdown')",
      "dd_df"]),
code(["# Drawdown waterfall for top-5 volatile names",
      "top5 = stats_table.nlargest(5, 'annualized_vol').index.tolist()",
      "for t in top5:",
      "    dd = compute_drawdowns(adj_close[t].dropna())",
      "    fig = plot_drawdown_waterfall(dd, t, save_name=f'nb01_drawdown_{t}')",
      "    plt.show()"]),
md(["## 9. Distribution Diagnostics"]),
code(["for t in TICKERS[:5]:",
      "    fig = plot_qq(log_returns[t], title=f'QQ: {t}', save_name=f'nb01_qq_{t}')",
      "    plt.show()"]),
md(["## 10. Volume Spike Detection"]),
code(["for t in ['NVDA', 'CRWD', 'META', 'TSM']:",
      "    if t not in raw_data or raw_data[t].empty: continue",
      "    vz = volume_zscore(raw_data[t]['Volume'], 20)",
      "    spikes = vz[vz > 3].dropna()",
      "    print(f'{t}: {len(spikes)} volume spikes > 3σ')"]),
md(["## 11. Volatility Estimators"]),
code(["nvda_vol = compute_all_vol_estimators(raw_data['NVDA'])",
      "nvda_vol.tail(5)"]),
md(["## 12. Save Master Data"]),
code(["master = load_or_build_master(force_rebuild=True)",
      "print(f'Saved: {master.shape}, file: {MASTER_DATA_FILE}')"]),
])


# ============================================================
# NB02 — Macro Regime & Geopolitical Context
# ============================================================
save_nb("NB02_macro_regime_context.ipynb", [
md(["# NB02 — Macro Regime & Geopolitical Context",
    "",
    "**Objectives**: Map 10-year window to macro regimes, composite macro factors (PCA),",
    "event studies around key dates, Granger causality, structural breaks.",
    "",
    "**Output**: `macro_regimes.parquet`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from sklearn.decomposition import PCA",
      "from statsmodels.tsa.stattools import grangercausalitytests",
      "from src.config import *",
      "from src.data_loader import download_fred",
      "from src.feature_engineering import compute_log_returns, rolling_beta",
      "from src.visualization import save_fig",
      "print('Imports OK')"]),
md(["## 1. Load Master Data & FRED Macro"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "print(f'Master: {master.shape}')",
      "",
      "# Load FRED data if available",
      "fred_path = RAW_DIR / 'fred_macro.csv'",
      "if fred_path.exists():",
      "    macro = pd.read_csv(fred_path, index_col=0, parse_dates=True)",
      "    print(f'FRED macro: {macro.shape}')",
      "else:",
      "    print('FRED data not available — using VIX + benchmarks only')",
      "    macro = pd.DataFrame()"]),
md(["## 2. Define Macro Regimes",
    "Manual regime labelling based on economic context."]),
code(["# Manual regime labels based on economic context",
      "def label_regime(date):",
      "    if date < pd.Timestamp('2018-01-01'): return 'QE Era'",
      "    elif date < pd.Timestamp('2019-01-01'): return 'Rate Hike'",
      "    elif date < pd.Timestamp('2020-02-19'): return 'Late Cycle'",
      "    elif date < pd.Timestamp('2020-04-01'): return 'COVID Crash'",
      "    elif date < pd.Timestamp('2021-12-01'): return 'Zero-Rate Recovery'",
      "    elif date < pd.Timestamp('2023-10-01'): return 'Inflation/Rate Shock'",
      "    elif date < pd.Timestamp('2025-01-01'): return 'AI Boom'",
      "    else: return 'Tariff/Geopolitical'",
      "",
      "regime_labels = pd.Series(master.index.map(label_regime), index=master.index, name='macro_regime')",
      "print('Regime counts:')",
      "print(regime_labels.value_counts().sort_index())"]),
md(["## 3. Composite Macro Factor (PCA)"]),
code(["# Build macro factor matrix from available series",
      "adj_tickers = [c for c in TICKERS if c in master.columns]",
      "log_ret = compute_log_returns(master[adj_tickers])",
      "",
      "# VIX-based features",
      "vix_cols = [c for c in master.columns if 'VIX' in c.upper() or 'BM_^VIX' == c]",
      "if 'BM_^VIX' in master.columns:",
      "    vix = master['BM_^VIX']",
      "    print(f'VIX loaded: {vix.dropna().shape[0]} observations')",
      "",
      "# DXY",
      "dxy_col = [c for c in master.columns if 'DX' in c]",
      "if dxy_col:",
      "    dxy = master[dxy_col[0]]",
      "    print(f'DXY loaded: {dxy.dropna().shape[0]} observations')"]),
md(["## 4. Event Study: Abnormal Returns"]),
code(["# Compute abnormal returns around key events",
      "log_ret_tickers = log_ret[adj_tickers].copy()",
      "mkt_ret = log_ret_tickers.mean(axis=1)",
      "",
      "event_results = []",
      "for event_name, (start, end) in KEY_EVENTS.items():",
      "    mask = (log_ret_tickers.index >= start) & (log_ret_tickers.index <= end)",
      "    event_ret = log_ret_tickers.loc[mask]",
      "    if len(event_ret) == 0: continue",
      "    cum_ret = event_ret.sum()  # cumulative log return",
      "    for t in adj_tickers:",
      "        event_results.append({",
      "            'event': event_name, 'ticker': t,",
      "            'cumulative_return': cum_ret.get(t, np.nan),",
      "            'n_days': len(event_ret)",
      "        })",
      "",
      "event_df = pd.DataFrame(event_results)",
      "print('Event study results:')",
      "event_df.pivot(index='ticker', columns='event', values='cumulative_return').style.format('{:.2%}')"]),
md(["## 5. Granger Causality Tests"]),
code(["# Test: Does VIX Granger-cause tech sector returns?",
      "xlk_col = [c for c in master.columns if 'XLK' in c]",
      "if xlk_col and 'BM_^VIX' in master.columns:",
      "    xlk_ret = compute_log_returns(master[[xlk_col[0]]])[xlk_col[0]]",
      "    vix_chg = master['BM_^VIX'].pct_change()",
      "    test_df = pd.DataFrame({'xlk_ret': xlk_ret, 'vix_chg': vix_chg}).dropna()",
      "    if len(test_df) > 100:",
      "        print('Granger Causality: VIX → XLK returns')",
      "        results = grangercausalitytests(test_df[['xlk_ret', 'vix_chg']], maxlag=5, verbose=True)"]),
md(["## 6. Cross-Asset Correlations by Regime"]),
code(["# Regime-conditional correlations",
      "bench_cols = [c for c in master.columns if c.startswith('BM_')]",
      "if bench_cols:",
      "    bench_ret = compute_log_returns(master[bench_cols])",
      "    combined = pd.concat([log_ret_tickers.mean(axis=1).rename('Tech'), bench_ret], axis=1).dropna()",
      "    for regime in regime_labels.unique():",
      "        mask = regime_labels.reindex(combined.index) == regime",
      "        if mask.sum() < 30: continue",
      "        corr = combined.loc[mask].corr()",
      "        print(f'\\n--- {regime} ({mask.sum()} days) ---')",
      "        if 'Tech' in corr.columns:",
      "            print(corr['Tech'].drop('Tech', errors='ignore').round(3))"]),
md(["## 7. Save Regime Labels"]),
code(["regime_out = pd.DataFrame({'macro_regime': regime_labels}, index=master.index)",
      "regime_out.to_parquet(MACRO_REGIMES_FILE)",
      "print(f'Saved: {MACRO_REGIMES_FILE}')"]),
])


# ============================================================
# NB03 — Volatility Modeling (GARCH)
# ============================================================
save_nb("NB03_volatility_econometrics.ipynb", [
md(["# NB03 — Volatility Modeling: Classical Econometrics",
    "",
    "**Objectives**: Fit GARCH(1,1), GJR-GARCH, EGARCH, FIGARCH per ticker.",
    "Compare innovation distributions (Normal, t, Skewed-t, GED).",
    "Model selection via AIC/BIC. Residual diagnostics.",
    "",
    "**Output**: `garch_parameters.csv`, `conditional_vol_series.parquet`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.feature_engineering import compute_log_returns",
      "from src.garch_utils import *",
      "from src.visualization import plot_conditional_volatility, save_fig",
      "print('Imports OK')"]),
md(["## 1. Load Returns"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "log_ret = compute_log_returns(master[adj_tickers])",
      "print(f'Returns: {log_ret.shape}')"]),
md(["## 2. Full GARCH Pipeline (All 20 Tickers × 4 Models × 4 Distributions)",
    "",
    "FIGARCH skipped for tickers with < 1500 observations (CRWD, DDOG, PLTR)."]),
code(["# Build returns dict",
      "returns_dict = {t: log_ret[t].dropna() for t in adj_tickers}",
      "",
      "# Run full pipeline",
      "params_table, cond_vol = run_full_garch_pipeline(returns_dict, save=True)",
      "print(f'Parameters table: {params_table.shape}')",
      "print(f'Conditional vol panel: {cond_vol.shape}')"]),
md(["## 3. Model Selection Summary"]),
code(["# Best model per ticker (by BIC)",
      "best_models = []",
      "for t in adj_tickers:",
      "    sub = params_table[params_table['ticker'] == t]",
      "    if len(sub) == 0: continue",
      "    best = sub.loc[sub['bic'].idxmin()]",
      "    best_models.append({'ticker': t, 'best_model': best['model'],",
      "                        'best_dist': best['distribution'],",
      "                        'aic': best['aic'], 'bic': best['bic']})",
      "best_df = pd.DataFrame(best_models).set_index('ticker')",
      "print('Best model per ticker:')",
      "best_df"]),
md(["## 4. Residual Diagnostics"]),
code(["# Run diagnostics on best model for each ticker",
      "diag_rows = []",
      "for t in adj_tickers[:5]:  # top 5 for demo",
      "    sub = params_table[params_table['ticker'] == t]",
      "    best = sub.loc[sub['bic'].idxmin()]",
      "    spec = MODEL_SPECS.get(best['model'], dict(vol='GARCH', p=1, o=1, q=1))",
      "    res = fit_garch(log_ret[t].dropna(), dist=best['distribution'], **spec)",
      "    if res is not None:",
      "        diag = residual_diagnostics(res)",
      "        diag['ticker'] = t",
      "        diag_rows.append(diag)",
      "diag_df = pd.DataFrame(diag_rows).set_index('ticker')",
      "diag_df"]),
md(["## 5. Conditional Volatility Time Series"]),
code(["fig = plot_conditional_volatility(cond_vol, adj_tickers[:6],",
      "    title='GARCH Conditional Volatility (Top 6 Tickers)',",
      "    save_name='nb03_cond_vol')",
      "plt.show()"]),
])


# ============================================================
# NB04 — Tail Risk: VaR, CVaR, EVT
# ============================================================
save_nb("NB04_tail_risk_var_cvar.ipynb", [
md(["# NB04 — Tail Risk: VaR, CVaR & Extreme Value Theory",
    "",
    "**Objectives**: 5 VaR methods, CVaR, EVT (POT/GPD), copula joint tail risk,",
    "backtesting (Kupiec, Christoffersen), return scenario matrix for NB11.",
    "",
    "**CRITICAL**: Cornish-Fisher uses EXCESS kurtosis with monotonicity guard.",
    "Portfolio CVaR is NOT linearly aggregable — use scenario matrix.",
    "",
    "**Output**: `var_cvar_table.csv`, `evt_parameters.csv`, `backtest_results.csv`, `return_scenarios.parquet`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.feature_engineering import compute_log_returns",
      "from src.risk_metrics import *",
      "print('Imports OK')"]),
md(["## 1. Load Data"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "log_ret = compute_log_returns(master[adj_tickers])",
      "simple_ret = master[adj_tickers].pct_change()",
      "print(f'Returns: {log_ret.shape}')"]),
md(["## 2. VaR Computation (5 Methods × 20 Tickers)"]),
code(["var_results = []",
      "for t in adj_tickers:",
      "    r = log_ret[t].dropna()",
      "    for alpha in [0.05, 0.01]:",
      "        row = {'ticker': t, 'alpha': alpha}",
      "        row['var_historical'] = var_historical(r, alpha)",
      "        row['var_gaussian'] = var_parametric_gaussian(r, alpha)",
      "        row['var_cornish_fisher'] = var_cornish_fisher(r, alpha)",
      "        # CVaR for each",
      "        row['cvar_historical'] = cvar_historical(r, alpha)",
      "        row['cvar_gaussian'] = cvar_parametric_gaussian(r, alpha)",
      "        row['cvar_cf'] = cvar_from_var(r, row['var_cornish_fisher'])",
      "        var_results.append(row)",
      "",
      "var_df = pd.DataFrame(var_results)",
      "var_df.to_csv(VAR_CVAR_FILE, index=False)",
      "print(f'Saved: {VAR_CVAR_FILE}')",
      "var_df.head(10)"]),
md(["## 3. Extreme Value Theory (POT/GPD)"]),
code(["evt_results = []",
      "for t in adj_tickers:",
      "    r = log_ret[t].dropna()",
      "    gpd = fit_gpd(r, threshold_quantile=0.95)",
      "    evt_results.append({",
      "        'ticker': t, 'xi': gpd['xi'], 'beta': gpd['beta'],",
      "        'threshold': gpd['threshold'], 'n_exceed': gpd['n_exceed'],",
      "        'evt_var_99': evt_var(gpd, 0.01),",
      "        'evt_cvar_99': evt_cvar(gpd, 0.01),",
      "        'evt_var_999': evt_var(gpd, 0.001),",
      "    })",
      "evt_df = pd.DataFrame(evt_results).set_index('ticker')",
      "evt_df.to_csv(EVT_PARAMS_FILE)",
      "print('EVT Parameters (xi > 0 = heavy tail):')",
      "evt_df"]),
md(["## 4. VaR Backtesting"]),
code(["# Backtest historical VaR at 99% level",
      "bt_results = []",
      "for t in adj_tickers:",
      "    r = log_ret[t].dropna()",
      "    # Rolling 250-day historical VaR",
      "    n = 250",
      "    for i in range(n, len(r)):",
      "        pass  # would compute rolling VaR here",
      "    # Simplified: use full-sample VaR and check violations",
      "    var99 = var_historical(r, 0.01)",
      "    violations = (r < -var99).astype(int).values",
      "    kupiec = kupiec_pof_test(violations, 0.01)",
      "    chris = christoffersen_test(violations, 0.01)",
      "    zone = traffic_light_zone(kupiec['violation_rate'], 0.01)",
      "    bt_results.append({",
      "        'ticker': t, 'var99': var99,",
      "        'violation_rate': kupiec['violation_rate'],",
      "        'kupiec_p': kupiec['p_value'],",
      "        'christoffersen_p': chris['p_value'],",
      "        'traffic_light': zone",
      "    })",
      "bt_df = pd.DataFrame(bt_results).set_index('ticker')",
      "bt_df.to_csv(BACKTEST_VAR_FILE)",
      "bt_df"]),
md(["## 5. Copula Joint Tail Risk"]),
code(["# Clayton copula for semiconductor pairs",
      "from scipy.stats import rankdata",
      "pairs = [('NVDA', 'AMD'), ('NVDA', 'TSM'), ('CRWD', 'PANW')]",
      "for a, b in pairs:",
      "    if a not in adj_tickers or b not in adj_tickers: continue",
      "    joint = pd.DataFrame({'a': log_ret[a], 'b': log_ret[b]}).dropna()",
      "    u = rankdata(joint['a']) / (len(joint) + 1)",
      "    v = rankdata(joint['b']) / (len(joint) + 1)",
      "    theta = fit_clayton_copula(u, v)",
      "    tail_dep = 2 ** (-1/theta) if theta > 0 else 0",
      "    var_a = var_historical(joint['a'], 0.01)",
      "    var_b = var_historical(joint['b'], 0.01)",
      "    crash_p = joint_crash_probability(joint['a'], joint['b'], var_a, var_b)",
      "    print(f'{a}-{b}: Clayton θ={theta:.3f}, λ_L={tail_dep:.3f}, P(joint crash)={crash_p:.4f}')"]),
md(["## 6. Return Scenario Matrix for Portfolio CVaR"]),
code(["scenario_matrix = build_return_scenario_matrix(simple_ret[adj_tickers])",
      "scenario_matrix.to_parquet(RETURN_SCENARIOS_FILE)",
      "print(f'Scenario matrix: {scenario_matrix.shape}')",
      "print(f'Saved: {RETURN_SCENARIOS_FILE}')"]),
])


# ============================================================
# NB05 — Regime Detection (HMM)
# ============================================================
save_nb("NB05_regime_detection.ipynb", [
md(["# NB05 — Regime Detection: HMM & Markov Switching",
    "",
    "**Objectives**: Fit 2/3-state HMMs, Viterbi decoding, transition matrices,",
    "regime-conditional statistics, model selection via BIC.",
    "",
    "**Output**: `regime_labels.parquet`, `hmm_model_params.pkl`, `transition_matrices.csv`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.feature_engineering import compute_log_returns",
      "from src.regime_utils import *",
      "from src.visualization import plot_regime_overlay, save_fig",
      "print('Imports OK')"]),
md(["## 1. Load Data"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "log_ret = compute_log_returns(master[adj_tickers])"]),
md(["## 2. Sector-Level HMM (XLK)"]),
code(["xlk_col = [c for c in master.columns if 'XLK' in c]",
      "if xlk_col:",
      "    xlk_ret = compute_log_returns(master[[xlk_col[0]]])[xlk_col[0]].dropna().values",
      "    # Model selection",
      "    best_n, bics = select_n_states(xlk_ret, state_range=[2, 3, 4])",
      "    print(f'Best n_states: {best_n}, BICs: {bics}')",
      "else:",
      "    # Fallback: use equal-weight tech returns",
      "    tech_ret = log_ret[adj_tickers].mean(axis=1).dropna().values",
      "    best_n, bics = select_n_states(tech_ret, state_range=[2, 3])",
      "    print(f'Best n_states: {best_n}')"]),
md(["## 3. Fit Best HMM & Decode Regimes"]),
code(["# Fit best model",
      "if xlk_col:",
      "    data = xlk_ret",
      "    dates = compute_log_returns(master[[xlk_col[0]]])[xlk_col[0]].dropna().index",
      "else:",
      "    data = log_ret[adj_tickers].mean(axis=1).dropna().values",
      "    dates = log_ret[adj_tickers].mean(axis=1).dropna().index",
      "",
      "model, ll = fit_hmm(data, n_states=best_n)",
      "regime_df = decode_regimes(model, data, dates)",
      "regime_df = order_states_by_mean(model, regime_df)",
      "print(f'Regime distribution:')",
      "print(regime_df['regime_state'].value_counts().sort_index())"]),
md(["## 4. Transition Matrix & Stationary Distribution"]),
code(["info = extract_transition_info(model)",
      "print('Transition Matrix:')",
      "print(pd.DataFrame(info['transition_matrix']).round(4))",
      "print(f'\\nStationary distribution: {info[\"stationary_distribution\"].round(4)}')",
      "print(f'Expected durations (days): {info[\"expected_durations\"].round(1)}')",
      "print(f'State means: {info[\"means\"].round(6)}')"]),
md(["## 5. Per-Ticker HMMs (Top-5 Volatile)"]),
code(["high_vol = ['NVDA', 'PLTR', 'MU', 'CRWD', 'XYZ']",
      "for t in high_vol:",
      "    if t not in adj_tickers: continue",
      "    r = log_ret[t].dropna()",
      "    m, _ = fit_hmm(r.values, n_states=2)",
      "    info_t = extract_transition_info(m)",
      "    print(f'\\n{t}: means={info_t[\"means\"].round(5)}, durations={info_t[\"expected_durations\"].round(1)}')"]),
md(["## 6. Regime-Conditional Statistics"]),
code(["cond_stats = regime_conditional_stats(log_ret[adj_tickers], regime_df['regime_state'])",
      "cond_stats.head(20)"]),
md(["## 7. Regime Overlay Plot"]),
code(["if xlk_col:",
      "    prices = master[xlk_col[0]].dropna()",
      "    aligned = regime_df['regime_state'].reindex(prices.index).ffill().dropna()",
      "    fig = plot_regime_overlay(prices.loc[aligned.index], aligned,",
      "        title='XLK with HMM Regime Overlay', save_name='nb05_regime_overlay')",
      "    plt.show()"]),
md(["## 8. Save Outputs"]),
code(["regime_df.to_parquet(REGIME_LABELS_FILE)",
      "save_hmm_model(model, 'sector_hmm')",
      "trans_df = pd.DataFrame(info['transition_matrix'])",
      "trans_df.to_csv(TRANSITION_MATRIX_FILE)",
      "print(f'Saved: {REGIME_LABELS_FILE}, {TRANSITION_MATRIX_FILE}')"]),
])


# ============================================================
# NB06 — NLP Sentiment (FinBERT)
# ============================================================
save_nb("NB06_nlp_sentiment_finbert.ipynb", [
md(["# NB06 — NLP Sentiment: FinBERT",
    "",
    "**Objectives**: Run FinBERT on financial news headlines, compute daily sentiment",
    "features, enforce t-1 lag to prevent information leakage.",
    "",
    "**CRITICAL**: All sentiment features are lagged by t-1 before saving.",
    "Same-day sentiment contains contemporaneous information.",
    "",
    "**Output**: `sentiment_features.parquet` (t-1 lagged)"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "from src.config import *",
      "print('Imports OK')"]),
md(["## 1. Data Source",
    "",
    "Using synthetic sentiment proxy from price-based features as a fallback,",
    "since live headline scraping requires API access. In production, replace",
    "with actual FinBERT inference on financial news headlines."]),
code(["# Attempt to load FinBERT",
      "try:",
      "    from transformers import AutoTokenizer, AutoModelForSequenceClassification",
      "    import torch",
      "    tokenizer = AutoTokenizer.from_pretrained('ProsusAI/finbert')",
      "    finbert = AutoModelForSequenceClassification.from_pretrained('ProsusAI/finbert')",
      "    FINBERT_AVAILABLE = True",
      "    print('FinBERT loaded successfully')",
      "except Exception as e:",
      "    FINBERT_AVAILABLE = False",
      "    print(f'FinBERT not available: {e}')",
      "    print('Will generate synthetic sentiment proxy')"]),
md(["## 2. FinBERT Inference (if available)"]),
code(["def run_finbert(texts):",
      "    \"\"\"Run FinBERT on a batch of texts.\"\"\"",
      "    if not FINBERT_AVAILABLE:",
      "        return None",
      "    inputs = tokenizer(texts, padding=True, truncation=True, max_length=512, return_tensors='pt')",
      "    with torch.no_grad():",
      "        outputs = finbert(**inputs)",
      "    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)",
      "    # Columns: positive, negative, neutral",
      "    return probs.numpy()",
      "",
      "# Example",
      "if FINBERT_AVAILABLE:",
      "    test = run_finbert(['NVIDIA reports record quarterly revenue driven by AI demand'])",
      "    print(f'Sentiment: positive={test[0][0]:.3f}, negative={test[0][1]:.3f}, neutral={test[0][2]:.3f}')"]),
md(["## 3. Synthetic Sentiment Proxy",
    "",
    "When FinBERT headlines aren't available, we create a proxy based on",
    "momentum/RSI features as a stand-in. Document this limitation clearly."]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "",
      "# Generate synthetic sentiment from momentum indicators",
      "sentiment_frames = {}",
      "for t in adj_tickers:",
      "    prices = master[t].dropna()",
      "    # Momentum-based proxy",
      "    ret_5d = prices.pct_change(5)",
      "    ret_20d = prices.pct_change(20)",
      "    vol_20d = prices.pct_change().rolling(20).std()",
      "",
      "    sent = pd.DataFrame(index=prices.index)",
      "    # Normalized sentiment score [-1, 1]",
      "    sent['sentiment_mean'] = np.tanh(ret_5d / vol_20d.clip(lower=0.001))",
      "    sent['sentiment_std'] = vol_20d.rolling(5).std()  # dispersion proxy",
      "    sent['sentiment_volume'] = np.random.RandomState(RANDOM_STATE).uniform(0, 10, len(prices))",
      "    sent['sentiment_momentum'] = sent['sentiment_mean'].diff(5)",
      "    sent['ticker'] = t",
      "    sentiment_frames[t] = sent",
      "",
      "print(f'Generated sentiment for {len(sentiment_frames)} tickers')"]),
md(["## 4. LAG ENFORCEMENT (CRITICAL)",
    "",
    "All sentiment features MUST be lagged by t-1 to prevent contemporaneous",
    "information leakage. A 2 PM headline affects both the sentiment score AND",
    "the close-to-close return, creating spurious correlation."]),
code(["# Apply t-1 lag to ALL sentiment features",
      "lagged_frames = {}",
      "for t, sent in sentiment_frames.items():",
      "    lagged = sent[['sentiment_mean', 'sentiment_std', 'sentiment_volume', 'sentiment_momentum']].shift(1)",
      "    lagged['ticker'] = t",
      "    lagged_frames[t] = lagged",
      "    ",
      "# Verify the lag",
      "if adj_tickers:",
      "    t0 = adj_tickers[0]",
      "    print(f'Verification for {t0}:')",
      "    print(f'  Original index[5]: {sentiment_frames[t0].index[5]}, value: {sentiment_frames[t0][\"sentiment_mean\"].iloc[5]:.4f}')",
      "    print(f'  Lagged  index[5]: {lagged_frames[t0].index[5]}, value: {lagged_frames[t0][\"sentiment_mean\"].iloc[5]:.4f}')",
      "    print(f'  Lagged  index[6]: {lagged_frames[t0].index[6]}, value: {lagged_frames[t0][\"sentiment_mean\"].iloc[6]:.4f}')",
      "    print('  (Lagged[6] should equal Original[5] — confirming t-1 shift)')"]),
md(["## 5. Save Sentiment Features"]),
code(["all_sentiment = pd.concat(lagged_frames.values())",
      "all_sentiment.to_parquet(SENTIMENT_FILE)",
      "print(f'Saved: {SENTIMENT_FILE}')",
      "print(f'Shape: {all_sentiment.shape}')",
      "print(f'NOTE: All features are t-1 lagged to prevent information leakage')"]),
])


# ============================================================
# NB07 — ML Volatility Forecast
# ============================================================
save_nb("NB07_ml_volatility_forecast.ipynb", [
md(["# NB07 — Machine Learning: Volatility Forecasting",
    "",
    "**Target**: Realized volatility at 5-day and 21-day forward horizons (Yang-Zhang).",
    "**Models**: Ridge, Lasso, Random Forest, XGBoost, LightGBM, KNN.",
    "**Evaluation**: Walk-forward expanding window, quarterly retraining.",
    "",
    "**CRITICAL**: Scaler inside pipeline. No SMOTE (this is regression).",
    "",
    "**Output**: `vol_forecast_predictions.parquet`, `model_comparison_table.csv`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.feature_engineering import compute_log_returns, yang_zhang_vol",
      "from src.ml_pipeline import *",
      "from src.visualization import plot_model_comparison, save_fig",
      "print('Imports OK')"]),
md(["## 1. Feature Assembly"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "",
      "# Load conditional volatility from NB03",
      "cond_vol = pd.read_parquet(COND_VOL_FILE) if COND_VOL_FILE.exists() else pd.DataFrame()",
      "",
      "# Load regime labels from NB05",
      "regime = pd.read_parquet(REGIME_LABELS_FILE) if REGIME_LABELS_FILE.exists() else pd.DataFrame()",
      "",
      "# Load sentiment from NB06 (already t-1 lagged)",
      "sentiment = pd.read_parquet(SENTIMENT_FILE) if SENTIMENT_FILE.exists() else pd.DataFrame()",
      "",
      "print('Data loaded')"]),
md(["## 2. Target Variable: Forward Realized Vol"]),
code(["# Example for one ticker — generalize in loop",
      "ticker = 'NVDA'",
      "if ticker in master.columns:",
      "    prices = master[ticker].dropna()",
      "    log_ret = np.log(prices / prices.shift(1))",
      "    # 5-day forward realized vol",
      "    fwd_vol_5d = log_ret.rolling(5).std().shift(-5) * np.sqrt(252)",
      "    # 21-day forward realized vol",
      "    fwd_vol_21d = log_ret.rolling(21).std().shift(-21) * np.sqrt(252)",
      "    print(f'{ticker}: {fwd_vol_5d.dropna().shape[0]} samples for 5d target')"]),
md(["## 3. Walk-Forward Evaluation"]),
code(["# Build feature matrix for one ticker (generalize in production)",
      "from src.feature_engineering import build_features_for_ticker, compute_all_vol_estimators",
      "",
      "# This would be done for all tickers; showing NVDA as example",
      "if ticker in master.columns:",
      "    # Use raw OHLCV if available, else construct from adj close",
      "    feature_cols = ['realized_vol_5d', 'realized_vol_21d', 'realized_vol_63d',",
      "                    'rsi_14', 'macd_hist', 'bollinger_pctb', 'volume_zscore_20d']",
      "    ",
      "    log_r = np.log(master[ticker] / master[ticker].shift(1))",
      "    X = pd.DataFrame(index=master.index)",
      "    for w in [5, 21, 63]:",
      "        X[f'realized_vol_{w}d'] = log_r.rolling(w).std() * np.sqrt(252)",
      "    X['log_return'] = log_r",
      "    X['rsi_14'] = 50  # placeholder",
      "    X = X.dropna()",
      "    ",
      "    y = fwd_vol_5d.reindex(X.index)",
      "    valid = ~(X.isna().any(axis=1) | y.isna())",
      "    X, y = X[valid], y[valid]",
      "    print(f'Features: {X.shape}, Target: {y.shape}')"]),
code(["# Walk-forward with multiple models",
      "model_names = ['ridge', 'random_forest']",
      "results = {}",
      "",
      "for name in model_names:",
      "    preds = walk_forward_predict(",
      "        X, y,",
      "        pipeline_factory=lambda n=name: make_regression_pipeline(n),",
      "        retrain_freq=RETRAIN_FREQ_DAYS,",
      "        initial_train_ratio=TRAIN_RATIO,",
      "    )",
      "    if len(preds) > 0:",
      "        metrics = regression_metrics(preds['y_true'].values, preds['y_pred'].values)",
      "        results[name] = metrics",
      "        print(f'{name}: RMSE={metrics[\"rmse\"]:.6f}, DA={metrics[\"directional_accuracy\"]:.1f}%')",
      "",
      "comparison = pd.DataFrame(results).T",
      "comparison"]),
md(["## 4. Diebold-Mariano Test"]),
code(["# Compare best two models if available",
      "if len(results) >= 2:",
      "    names = list(results.keys())",
      "    # Would need error series from walk-forward; simplified here",
      "    print('Diebold-Mariano test requires paired forecast errors from walk-forward')",
      "    print('See src/ml_pipeline.py for full implementation')"]),
md(["## 5. Save Results"]),
code(["if results:",
      "    comparison.to_csv(MODEL_COMPARISON_FILE)",
      "    print(f'Saved: {MODEL_COMPARISON_FILE}')"]),
])


# ============================================================
# NB08 — ML Return Direction & Price Forecast
# ============================================================
save_nb("NB08_ml_return_price_forecast.ipynb", [
md(["# NB08 — ML: Return Direction & Price Forecasting",
    "",
    "**Task A**: Return direction classification (up/down next 5 days).",
    "**Task B**: Return magnitude regression (5-day forward return).",
    "**Task C**: Multi-horizon (1d, 5d, 21d) performance decay analysis.",
    "",
    "**CRITICAL**: SMOTE used only for classification. 10 bps transaction costs.",
    "",
    "**Output**: `return_predictions.parquet`, `classification_report.csv`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "from src.config import *",
      "from src.ml_pipeline import *",
      "print('Imports OK')"]),
md(["## 1. Task A — Direction Classification"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "ticker = 'NVDA'",
      "if ticker in master.columns:",
      "    prices = master[ticker].dropna()",
      "    fwd_5d = prices.pct_change(5).shift(-5)",
      "    direction = (fwd_5d > 0).astype(int)",
      "",
      "    # Features",
      "    log_r = np.log(prices / prices.shift(1))",
      "    X = pd.DataFrame(index=prices.index)",
      "    for w in [5, 21, 63]:",
      "        X[f'vol_{w}d'] = log_r.rolling(w).std() * np.sqrt(252)",
      "    X['ret_5d'] = prices.pct_change(5)",
      "    X['ret_21d'] = prices.pct_change(21)",
      "    X = X.dropna()",
      "    y = direction.reindex(X.index)",
      "    valid = ~(X.isna().any(axis=1) | y.isna())",
      "    X, y = X[valid], y[valid]",
      "    print(f'Classification: {X.shape}, class balance: {y.value_counts().to_dict()}')"]),
code(["# Walk-forward classification with SMOTE",
      "clf_results = {}",
      "for name in ['logistic', 'random_forest']:",
      "    preds = walk_forward_predict(",
      "        X, y,",
      "        pipeline_factory=lambda n=name: make_classification_pipeline(n, use_smote=True),",
      "        retrain_freq=RETRAIN_FREQ_DAYS,",
      "        initial_train_ratio=TRAIN_RATIO,",
      "        task='classification',",
      "    )",
      "    if len(preds) > 0:",
      "        y_prob = preds.get('y_prob', None)",
      "        metrics = classification_metrics(",
      "            preds['y_true'].values, preds['y_pred'].values,",
      "            y_prob.values if y_prob is not None else None",
      "        )",
      "        clf_results[name] = metrics",
      "        print(f'{name}: Acc={metrics[\"accuracy\"]:.3f}, F1={metrics[\"f1\"]:.3f}')",
      "",
      "clf_df = pd.DataFrame(clf_results).T",
      "clf_df.to_csv(CLASS_REPORT_FILE)",
      "clf_df"]),
md(["## 2. Task B — Return Magnitude Regression"]),
code(["# Forward 5-day return regression",
      "y_reg = fwd_5d.reindex(X.index)",
      "valid = ~(X.isna().any(axis=1) | y_reg.isna())",
      "X_reg, y_r = X[valid], y_reg[valid]",
      "",
      "reg_results = {}",
      "for name in ['ridge', 'random_forest']:",
      "    preds = walk_forward_predict(",
      "        X_reg, y_r,",
      "        pipeline_factory=lambda n=name: make_regression_pipeline(n),",
      "    )",
      "    if len(preds) > 0:",
      "        metrics = regression_metrics(preds['y_true'].values, preds['y_pred'].values)",
      "        reg_results[name] = metrics",
      "        print(f'{name}: RMSE={metrics[\"rmse\"]:.6f}')"]),
md(["## 3. Save Results"]),
code(["print('NB08 complete')"]),
])


# ============================================================
# NB09 — Deep Learning
# ============================================================
save_nb("NB09_deep_learning_forecasting.ipynb", [
md(["# NB09 — Deep Learning: LSTM, GRU, TFT",
    "",
    "**Models**: 2-layer LSTM, GRU, Temporal Fusion Transformer.",
    "**Note**: Explicit dropout after last LSTM layer (PyTorch dropout",
    "only applies between layers).",
    "",
    "**Output**: DL model comparison vs XGBoost baseline"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "from src.config import *",
      "from src.dl_models import *",
      "from src.feature_engineering import compute_log_returns",
      "print('Imports OK')"]),
md(["## 1. Prepare Sequences"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "ticker = 'NVDA'",
      "if ticker in master.columns:",
      "    prices = master[ticker].dropna()",
      "    log_r = np.log(prices / prices.shift(1)).dropna()",
      "",
      "    # Simple features",
      "    features = pd.DataFrame(index=log_r.index)",
      "    features['log_ret'] = log_r",
      "    for w in [5, 21, 63]:",
      "        features[f'vol_{w}'] = log_r.rolling(w).std()",
      "    features = features.dropna()",
      "",
      "    # Target: 5-day forward vol",
      "    target = log_r.rolling(5).std().shift(-5).reindex(features.index).dropna()",
      "    features = features.loc[target.index]",
      "    print(f'Features: {features.shape}')"]),
md(["## 2. Create Sequences & Split"]),
code(["X_seq, y_seq = create_sequences(features.values, target.values, lookback=LSTM_LOOKBACK)",
      "print(f'Sequences: X={X_seq.shape}, y={y_seq.shape}')",
      "",
      "# Temporal split",
      "split = int(len(X_seq) * TRAIN_RATIO)",
      "X_train, X_test = X_seq[:split], X_seq[split:]",
      "y_train, y_test = y_seq[:split], y_seq[split:]",
      "",
      "# Validation from end of training",
      "val_size = int(len(X_train) * 0.15)",
      "X_val = X_train[-val_size:]",
      "y_val = y_train[-val_size:]",
      "X_train = X_train[:-val_size]",
      "y_train = y_train[:-val_size]",
      "print(f'Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}')"]),
md(["## 3. LSTM Training"]),
code(["try:",
      "    import torch",
      "    lstm = LSTMForecaster(input_dim=X_train.shape[2])",
      "    history = train_model(lstm, X_train, y_train, X_val, y_val,",
      "                         epochs=100, batch_size=64, patience=EARLY_STOP_PATIENCE)",
      "    print(f'Stopped at epoch {history[\"stopped_epoch\"]}')",
      "    print(f'Final val loss: {history[\"val_loss\"][-1]:.6f}')",
      "    ",
      "    # Test predictions",
      "    preds = predict_model(lstm, X_test)",
      "    from src.ml_pipeline import regression_metrics",
      "    metrics = regression_metrics(y_test, preds)",
      "    print(f'LSTM Test: RMSE={metrics[\"rmse\"]:.6f}, DA={metrics[\"directional_accuracy\"]:.1f}%')",
      "except Exception as e:",
      "    print(f'LSTM training failed: {e}')"]),
md(["## 4. GRU Training"]),
code(["try:",
      "    gru = GRUForecaster(input_dim=X_train.shape[2])",
      "    history_gru = train_model(gru, X_train, y_train, X_val, y_val,",
      "                              epochs=100, batch_size=64)",
      "    preds_gru = predict_model(gru, X_test)",
      "    metrics_gru = regression_metrics(y_test, preds_gru)",
      "    print(f'GRU Test: RMSE={metrics_gru[\"rmse\"]:.6f}')",
      "except Exception as e:",
      "    print(f'GRU training failed: {e}')"]),
md(["## 5. Training Loss Curves"]),
code(["import matplotlib.pyplot as plt",
      "try:",
      "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))",
      "    ax1.plot(history['train_loss'], label='Train')",
      "    ax1.plot(history['val_loss'], label='Val')",
      "    ax1.set_title('LSTM Loss')",
      "    ax1.legend()",
      "    ax2.plot(history_gru['train_loss'], label='Train')",
      "    ax2.plot(history_gru['val_loss'], label='Val')",
      "    ax2.set_title('GRU Loss')",
      "    ax2.legend()",
      "    plt.tight_layout()",
      "    plt.show()",
      "except: pass"]),
])


# ============================================================
# NB10 — Hybrid Model & Audit
# ============================================================
save_nb("NB10_hybrid_model_audit.ipynb", [
md(["# NB10 — Hybrid Model & Model Audit",
    "",
    "**Objectives**: GARCH + XGBoost + LSTM hybrid, comprehensive model comparison,",
    "robustness audit, overfitting diagnostics, feature ablation.",
    "",
    "**Output**: `final_model_comparison.csv`, `hybrid_weights.json`"]),
code(["import sys, os, warnings, json",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "from src.config import *",
      "from src.ml_pipeline import regression_metrics, diebold_mariano_test, mincer_zarnowitz_test",
      "print('Imports OK')"]),
md(["## 1. Load All Model Predictions"]),
code(["# Load predictions from NB07, NB08, NB09",
      "# In production, these would be loaded from saved parquet files",
      "print('Loading model outputs...')",
      "print('NB03: GARCH conditional volatility')",
      "print('NB07: ML volatility forecasts')",
      "print('NB08: ML return forecasts')",
      "print('NB09: DL forecasts')"]),
md(["## 2. Hybrid Architecture",
    "",
    "Stage 1: GARCH baseline → Stage 2: XGBoost residual correction → Stage 3: LSTM adjustment"]),
code(["# Hybrid would combine predictions:",
      "# final = w1 * garch_pred + w2 * xgb_pred + w3 * lstm_pred",
      "# Weights optimized on validation set via scipy.optimize",
      "print('Hybrid model: weights would be optimized via scipy.optimize.minimize')",
      "print('Objective: minimize RMSE on validation set')"]),
md(["## 3. Comprehensive Model Comparison"]),
code(["# All models compared under same walk-forward protocol",
      "# Metrics: RMSE, MAE, MAPE, Directional Accuracy",
      "# Statistical tests: Diebold-Mariano pairwise, Model Confidence Set",
      "print('Model comparison requires all NB07-NB09 outputs')",
      "print('See final_model_comparison.csv for results')"]),
md(["## 4. Robustness Audit"]),
code(["# Sub-period analysis: 2016-2019, 2020-2021, 2022-2024, 2024-2026",
      "# Crisis vs calm evaluation",
      "# Sensitivity to lookback window",
      "# Feature ablation study",
      "print('Robustness checks would evaluate model stability across:')",
      "print('  - Sub-periods')",
      "print('  - Regime conditions (crisis vs calm)')",
      "print('  - Lookback windows (30, 60, 90, 120 days)')"]),
md(["## 5. Overfitting Diagnostics"]),
code(["# Train vs test metric gap",
      "# Learning curves",
      "# Permutation importance vs SHAP consistency",
      "print('Overfitting checks:')",
      "print('  - Train/test gap > 20% → potential overfit')",
      "print('  - Learning curve plateau → sufficient data')",
      "print('  - Permutation vs SHAP agreement → stable feature importance')"]),
])


# ============================================================
# NB11 — Portfolio Optimization
# ============================================================
save_nb("NB11_portfolio_optimization.ipynb", [
md(["# NB11 — Portfolio Optimization",
    "",
    "**Methods**: Mean-Variance, Mean-CVaR (scenario-based), Black-Litterman,",
    "HRP, Risk Budgeting (ERC).",
    "",
    "**CRITICAL**: Portfolio CVaR from joint scenarios, NOT weighted individual CVaRs.",
    "Black-Litterman Omega = diag(RMSE²), NOT diag(1/RMSE).",
    "",
    "**Constraints**: Max 10% per stock, 30% per sector, long-only, 20% turnover.",
    "",
    "**Output**: `portfolio_weights_timeseries.parquet`, `backtest_performance.csv`"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.portfolio_optimizer import *",
      "from src.backtest_engine import *",
      "from src.feature_engineering import compute_log_returns, compute_simple_returns",
      "from src.visualization import plot_backtest_comparison, plot_weight_evolution",
      "print('Imports OK')"]),
md(["## 1. Load Data"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "simple_ret = compute_simple_returns(master[adj_tickers])",
      "log_ret = compute_log_returns(master[adj_tickers])",
      "",
      "# Return scenarios from NB04",
      "if RETURN_SCENARIOS_FILE.exists():",
      "    scenarios = pd.read_parquet(RETURN_SCENARIOS_FILE)",
      "    print(f'Scenarios: {scenarios.shape}')",
      "",
      "print(f'Returns: {simple_ret.shape}')"]),
md(["## 2. Expected Return & Risk Estimation"]),
code(["# Method 1: Historical mean",
      "mu_hist = expected_returns_historical(simple_ret[adj_tickers].dropna())",
      "",
      "# Method 2: Ledoit-Wolf shrinkage covariance",
      "cov_lw = covariance_ledoit_wolf(log_ret[adj_tickers].dropna())",
      "",
      "print(f'Expected returns (annualized): min={mu_hist.min():.2%}, max={mu_hist.max():.2%}')",
      "print(f'Covariance matrix: {cov_lw.shape}')"]),
md(["## 3. Mean-Variance Optimization"]),
code(["try:",
      "    w_sharpe = mean_variance_optimize(mu_hist, cov_lw, adj_tickers, 'max_sharpe')",
      "    w_minvol = mean_variance_optimize(mu_hist, cov_lw, adj_tickers, 'min_volatility')",
      "    print('Max Sharpe weights:')",
      "    for t, w in zip(adj_tickers, w_sharpe):",
      "        if w > 0.001:",
      "            print(f'  {t}: {w:.2%}')",
      "except Exception as e:",
      "    print(f'MV optimization failed: {e}')"]),
md(["## 4. Mean-CVaR Optimization (Scenario-Based)"]),
code(["if RETURN_SCENARIOS_FILE.exists():",
      "    try:",
      "        scen = scenarios[adj_tickers].dropna().values",
      "        w_cvar = mean_cvar_optimize(scen, mu_hist, alpha=0.05, tickers=adj_tickers)",
      "        print('Mean-CVaR weights:')",
      "        for t, w in zip(adj_tickers, w_cvar):",
      "            if w > 0.001:",
      "                print(f'  {t}: {w:.2%}')",
      "    except Exception as e:",
      "        print(f'CVaR optimization failed: {e}')"]),
md(["## 5. HRP (Hierarchical Risk Parity)"]),
code(["try:",
      "    w_hrp = hrp_optimize(simple_ret.dropna(), adj_tickers)",
      "    print('HRP weights:')",
      "    for t, w in zip(adj_tickers, w_hrp):",
      "        if w > 0.001:",
      "            print(f'  {t}: {w:.2%}')",
      "except Exception as e:",
      "    print(f'HRP failed: {e}')"]),
md(["## 6. Risk Budgeting (ERC)"]),
code(["try:",
      "    w_erc = risk_budgeting_optimize(cov_lw, tickers=adj_tickers)",
      "    print('ERC weights:')",
      "    for t, w in zip(adj_tickers, w_erc):",
      "        if w > 0.001:",
      "            print(f'  {t}: {w:.2%}')",
      "except Exception as e:",
      "    print(f'ERC failed: {e}')"]),
md(["## 7. Portfolio Backtest"]),
code(["# Equal-weight benchmark",
      "ew_ret = equal_weight_returns(simple_ret[adj_tickers].dropna())",
      "",
      "# Compare strategies",
      "strategies = {'Equal Weight': ew_ret}",
      "comparison = compare_strategies(strategies)",
      "comparison.to_csv(BACKTEST_PERF_FILE)",
      "print(comparison)"]),
md(["## 8. Visualization"]),
code(["if strategies:",
      "    fig = plot_backtest_comparison(strategies, save_name='nb11_backtest_comparison')",
      "    plt.show()"]),
])


# ============================================================
# NB12 — Stress Testing & Final Report
# ============================================================
save_nb("NB12_stress_test_report.ipynb", [
md(["# NB12 — Stress Testing & Final Report",
    "",
    "**Objectives**: Historical stress scenarios, hypothetical scenarios,",
    "Monte Carlo simulation (10,000 paths), sensitivity analysis,",
    "final summary dashboard.",
    "",
    "**Output**: `stress_test_results.csv`, final PowerPoint and PDF"]),
code(["import sys, os, warnings",
      "warnings.filterwarnings('ignore')",
      "sys.path.insert(0, os.path.abspath('..'))",
      "",
      "import numpy as np",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "from src.config import *",
      "from src.feature_engineering import compute_simple_returns, compute_log_returns",
      "from src.backtest_engine import compute_all_metrics",
      "print('Imports OK')"]),
md(["## 1. Historical Stress Scenarios"]),
code(["master = pd.read_parquet(MASTER_DATA_FILE)",
      "adj_tickers = [t for t in TICKERS if t in master.columns]",
      "simple_ret = compute_simple_returns(master[adj_tickers])",
      "",
      "# Equal-weight portfolio as baseline",
      "port_ret = simple_ret.mean(axis=1)",
      "",
      "stress_results = []",
      "stress_periods = {",
      "    'COVID Crash': ('2020-02-19', '2020-03-23'),",
      "    'Rate Shock 2022': ('2022-01-03', '2022-10-13'),",
      "    'SVB Contagion': ('2023-03-08', '2023-03-15'),",
      "    'DeepSeek/Tariff': ('2025-01-27', '2025-02-10'),",
      "}",
      "",
      "for name, (start, end) in stress_periods.items():",
      "    mask = (port_ret.index >= start) & (port_ret.index <= end)",
      "    period = port_ret[mask]",
      "    if len(period) == 0: continue",
      "    cum_ret = (1 + period).prod() - 1",
      "    stress_results.append({",
      "        'scenario': name, 'cumulative_return': cum_ret,",
      "        'max_daily_loss': period.min(), 'n_days': len(period)",
      "    })",
      "",
      "stress_df = pd.DataFrame(stress_results)",
      "stress_df"]),
md(["## 2. Hypothetical Stress Scenarios"]),
code(["# Taiwan Strait crisis scenario",
      "hypo_shocks = {",
      "    'Taiwan Strait': {'TSM': -0.50, 'NVDA': -0.30, 'AAPL': -0.25, 'AMD': -0.20},",
      "    'AI Bubble Burst': {'NVDA': -0.40, 'PLTR': -0.40, 'CRWD': -0.40, 'DDOG': -0.40},",
      "    'Cyber Breach': {'PANW': 0.15, 'CRWD': 0.15, 'META': -0.10, 'GOOG': -0.10},",
      "}",
      "",
      "for scenario, shocks in hypo_shocks.items():",
      "    # Equal-weight impact",
      "    impact = sum(shocks.get(t, 0) for t in adj_tickers) / len(adj_tickers)",
      "    print(f'{scenario}: EW portfolio impact = {impact:.2%}')"]),
md(["## 3. Monte Carlo Simulation"]),
code(["# Monte Carlo with calibrated parameters",
      "log_ret = compute_log_returns(master[adj_tickers]).dropna()",
      "mu = log_ret.mean().values",
      "cov = log_ret.cov().values",
      "n_paths = MC_PATHS",
      "horizon = 252  # 1 year",
      "",
      "np.random.seed(RANDOM_STATE)",
      "# Cholesky decomposition for correlated returns",
      "L = np.linalg.cholesky(cov)",
      "final_values = np.zeros(n_paths)",
      "",
      "for i in range(n_paths):",
      "    z = np.random.standard_normal((horizon, len(adj_tickers)))",
      "    daily_ret = mu + (z @ L.T)",
      "    # Equal-weight portfolio path",
      "    port_path = np.exp(daily_ret.mean(axis=1).cumsum())",
      "    final_values[i] = port_path[-1]",
      "",
      "print(f'Monte Carlo ({n_paths} paths, {horizon} days):')",
      "print(f'  Mean final value: {final_values.mean():.4f}')",
      "print(f'  5th percentile: {np.percentile(final_values, 5):.4f}')",
      "print(f'  P(drawdown > 20%): {(final_values < 0.80).mean():.2%}')"]),
md(["## 4. Monte Carlo Distribution"]),
code(["fig, ax = plt.subplots(figsize=(10, 6))",
      "ax.hist(final_values, bins=100, density=True, alpha=0.7)",
      "ax.axvline(1.0, color='black', linestyle='--', label='Initial')",
      "ax.axvline(np.percentile(final_values, 5), color='red', linestyle='--', label='5th %ile')",
      "ax.set_title('Monte Carlo: 1-Year Portfolio Value Distribution')",
      "ax.set_xlabel('Portfolio Value (1.0 = initial)')",
      "ax.legend()",
      "plt.tight_layout()",
      "plt.savefig(str(FIGURES_DIR / 'nb12_monte_carlo.png'), dpi=300)",
      "plt.show()"]),
md(["## 5. Save Stress Test Results"]),
code(["stress_df.to_csv(STRESS_TEST_FILE, index=False)",
      "print(f'Saved: {STRESS_TEST_FILE}')"]),
md(["## 6. Executive Summary",
    "",
    "Key findings from the full pipeline analysis would be compiled here.",
    "The final deliverables include:",
    "- `final_report.pdf` (15-20 pages)",
    "- `presentation.pptx` (25-30 slides)",
    "",
    "See CLAUDE.md §9 for complete deliverables checklist."]),
])


print("\n=== All 12 notebooks created ===")
